version: '3'
services:

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: app-image
    environment:
      - FLASK_APP=hello.py
      - FLASK_ENV=production
      - SERVER_NAME=localhost.dev
    tty: true
    stdin_open: true
    ports:
      - "80:5000"
    volumes:
      - ../../app:/app
    working_dir: "/app"
    command: flask run --host=0.0.0.0
    networks:
      - dev

networks:
  dev:
    external: true
