######################################################################
# Automatically generated by qmake (3.0) Wed Nov 13 21:14:10 2013
######################################################################

TEMPLATE = app
TARGET = FindDialog
INCLUDEPATH += .
QT += widgets gui

# Input
HEADERS += FindDialog.h
SOURCES += FindDialog.cpp main.cpp
