[pytest]
norecursedirs = docs *.egg-info .git appdir .tox api config dist node_modules public reports src e2e_test
bdd_features_base_dir = features/
python_class = *Test
addopts=-vvl
markers =
    web

junit_suite_name = "Skeleton Lambda Tests"
junit_duration_report = call

