AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  youtube-music-mcp-server

  Sample SAM Template for youtube-music-mcp-server

Globals:
  Function:
    Timeout: 3

Resources:
  YoutubeMusicMcpServerApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true

  YoutubeMusicMcpServerFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: ./
      Handler: youtube_music_mcp_server.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
            RestApiId: !Ref YoutubeMusicMcpServerApi
      Environment:
        Variables:
          YOUTUBE_SECRETS: !Ref YoutubeSecrets
          YOUTUBE_TOKEN: !Ref YoutubeToken
    Metadata:
      SamResourceId: YoutubeMusicMcpServerFunction

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
        - ApiId: !Ref YoutubeMusicMcpServerApi
          Stage: Prod
      Quota:
        Limit: 10000
        Period: DAY
      Throttle:
        BurstLimit: 20
        RateLimit: 10

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Enabled: true

  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

Parameters:
  YoutubeSecrets:
    Type: String
    Description: Contents of the client_secrets.json file
  YoutubeToken:
    Type: String
    Description: Contents of the youtube.token file

Outputs:
  ApiKey:
    Description: "API Key for the Youtube Music MCP Server"
    Value: !Ref ApiKey
