######################################################################
# Automatically generated by qmake (3.0) Wed Nov 13 19:51:33 2013
######################################################################

TEMPLATE = app
TARGET = HelloWorld
INCLUDEPATH += .
QT += widgets gui

# Input
SOURCES += main.cpp
