######################################################################
# Automatically generated by qmake (3.0) Wed Nov 13 20:11:34 2013
######################################################################

TEMPLATE = app
TARGET = FirstInteraction
INCLUDEPATH += .
QT = gui widgets

# Input
SOURCES += main.cpp
