FROM %%FROM_IMAGE%%

MAINTAINER Damian Ziobro <damian@xmementoit.com>

ENV USER docker
ENV HOME /home/$USER

RUN apt-get -y update && apt-get -y install sudo puppet 

RUN useradd -ms /bin/bash $USER && adduser $USER sudo && echo 'docker:docker123' | chpasswd && \
    echo "ALL ALL=NOPASSWD:  /usr/bin/puppet" >> /etc/sudoers

EXPOSE 22 80 

ADD puppet/manifests/* /etc/puppet/manifests/

#========================================================
# switching to user docker
USER $USER
ENV USER docker
ENV HOME /home/$USER

WORKDIR $HOME

RUN sudo puppet apply /etc/puppet/manifests/install.pp
