apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.serviceName }} 
spec:
  ports:
  - name: 80-80
    port: {{ .Values.sourcePort }}
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.appName }}
  type: ClusterIP
status:
  loadBalancer: {}
