VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = 'ubuntu/xenial64'

  config.vm.provision "shell", path: "install_puppet.sh"
  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "../puppet/manifests"
    puppet.manifest_file = "install.pp"
  end

end
